apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patrones-output-pvc
  namespace: workloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Replace with a storageClass available in your cluster, e.g. "standard", "gp2", "nfs-sc", or remove to use default
  storageClassName: standard
